# Generated by Django 3.2.2 on 2021-05-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single', '0002_single_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single',
            old_name='artist',
            new_name='Single',
        ),
    ]
